### ISSUE TITLE
Feature Request: Timestamps for rolls

### ISSUE THREAD

**Issue by ocdtrekkie** [frigginglorious/dieStorm#1]
That's it. Literally the only thing this app needs to be perfect. I'd love to have it say: 

 Jacob Weisz rolled a d100 at 2016/04/20 23:28:00: 95
or
2016/04/20 23:28:00 - Jacob Weisz rolled a d100: 95 

Or something similar.

**Comment by frigginglorious** [comment]
I actually got an issue, and I actually fixed it. Thats awesome times 2 :)

![image](https://cloud.githubusercontent.com/assets/3982200/14699640/06bdb42a-075f-11e6-99fb-8b3caf551d78.png)

**Comment by ocdtrekkie** [comment]
:D
